### ISSUE TITLE
Interface segregation principle is broken  

### ISSUE THREAD

**Issue by kandy** [phly/http#25]
Please move all with* to separate interface like *Builder. 
Its allow create separate implementation that create new object only in build() calls for example.

**Comment by weierophinney** [comment]
The interfaces are from PSR-7, and represent [value objects](http://en.wikipedia.org/wiki/Value_object), and are thus examples of [immutable objects](http://en.wikipedia.org/wiki/Immutable_object). The paradigm used for the various `with` and `without` methods is essentially [copy-on-write](http://en.wikipedia.org/wiki/Copy-on-write). Since the goal is to model and specify value objects, the `with` methods are one aspect of the specified behavior (which allows for not just retrieval of values, but iterative creation of requests and responses).
