### ISSUE TITLE
Cookie issue as discussed

### ISSUE THREAD

**Issue by harikt** [phly/http#49]
Hi @weierophinney , 

As we already discussed in irc . I am keeping the text .

```
regarding cookie in psr-7 
<harikt> Did you purposefully left the cookie in the phly/http ?
<weierophinney> harikt: I have. Jeremy is correct: we chose specifically not to model cookies and other complex headers, as you can have utility functions/classes for doing that work. If you do, you can inject the actual header value, and at that point, we don't even need to call setcookie() (which just emits a formated header)
* dstockto (~dstockto@50-205-21-218-static.hfc.comcastbusiness.net) has joined #zftalk
<harikt> ok thanks weierophinney though I don't know how it will be done .
<weierophinney> harikt: If I don't write it, simensen likely will, and soon. :)
<harikt> was asking simensen about it 
<harikt> Just wanted to share with you also the same concern.
<weierophinney> It's not hard; the format is well-known. What you'd end up doing is something like $response->withAddedHeader('Set-Cookie', new Cookie(...))
* alea123 has quit ()
<harikt> I have seen things like this https://github.com/auraphp/Aura.Web/blob/develop-2/src/Response.php#L107
<harikt> but as you said about modelling different sort of data , I am with drawing .
<weierophinney> harikt: we cover already in the meta doc that we're not providing interfaces/solutions/etc for complex header values, and Set-Cookie was specifically mentioned.
```

And thanks to @simensen pointing the link to https://github.com/php-fig/fig-standards/blob/master/proposed/http-message-meta.md#what-about-special-header-values

After that I was looking at Guzzle and Slim to see how the cookie is done .

I noticed a method `withCookie` and `withoutCookie` at @slimphp  https://github.com/slimphp/Slim/blob/3b708f78657199dd4d7afe834126438d9a43cd17/Slim/Http/Response.php#L537-L543 .

After looking into it, I have a feeling implementors will implement different ways than the one you mentioned `withAddedHeader('Set-Cookie', new Cookie(...))`  . 

I did checked https://github.com/guzzle/psr7 , but in a quick look didn't find anything, may be for its WIP .

So this cookie will eventually breaks the reusability of the module / packages we are aiming when `withCookie` and `withAddedHeader` cookie are implemented I belive.

May be we should make a utlility library ASAP than later . 

Thank you

**Comment by weierophinney** [comment]
@simensen is working on a PoC in https://github.com/dflydev/dflydev-fig-cookies

I don't agree with this conclusion:

> So this cookie will eventually breaks the reusability of the module / packages we are aiming when withCookie and withAddedHeader cookie are implemented I belive.

When you're programming to the interface, you will call `withAddedHeader('Set-Cookie', $value)`, where `$value` is a `string` or object defining `__toString()`. This ensures that the message itself does not need any awareness of cookies, because it's aware of how cookies are communicated: via headers. It also means that any process emitting the response message only needs to worry about headers and the response body, and not whether or not any cookies are present, because they will be present already, _as headers_.

What it means to end-users is that they will have a dependency on `psr/http-message` **and** some other package that provides a way to work with cookies. This makes sense to me. In ZF and Guzzle, you have code that acts as a "cookie jar"; that code can now be abstracted and made into a single-purpose library, allowing somebody or some group of people to give it their full attention. If you want to work with encrypted cookies, this becomes the domain of such a package — and not part of the message implementation. Users will do something like this:

```php
$cookieJar = new ClientCookies($request->getHeader('Cookie'));

// or

$cookieJar = new ServerCookies($response->getHeader('Set-Cookie'));
```

work with the values, and potentially re-seed the message with the values:

```php
return $response->withHeader('Set-Cookie', $cookieJar->getCookies());
```

I think this will be quite useful, and helps promote the goal of solid, single-purpose libraries doing one thing well.

**Comment by harikt** [comment]
Hi @weierophinney , 

Yes I have noticed the work on Cookies by Beau.
