### ISSUE TITLE
May be a common method to easily proxy the write to stream ?

### ISSUE THREAD

**Issue by harikt** [phly/http#50]
In conduit there is a write method which is a proxy. https://github.com/phly/conduit/blob/1ebb5c014a8956366a96f5f02b4fe0b3a3cee5fb/src/Http/Response.php#L52-L60

It seems good to have on the ResponseInterface for people use the same method name than a different one on another implementation. 

I was using the proxy method and later came to know this was not the method in the ResponseInterface . I am still not sure though, for this will may bring more over head cloning 

```php
public function write($data)
{
    $new = clone $this;
    $new->getBody()->write($data);
    return $new
}
```

What do you think ?

**Comment by harikt** [comment]
To be more clear I am asking to bring the `write` method to PSR-7 response interface.

**Comment by weierophinney** [comment]
I added that proxy method to Conduit to mimic the API of Connect. The way I achieve it is by decorating the passed `ResponseInterface` instance, which, if middleware extends Conduit's `Middleware` class, can be guaranteed to occur.

That said, I should likely drop it.

We don't have it in the PSR-7 interfaces because it violates the Law of Demeter; users would be calling an operation on one object to effect a change on the other object.
