### ISSUE TITLE
__toString in response

### ISSUE THREAD

**Issue by Mech7** [phly/http#64]
It would be nice if there was a convience method __toString in the response that we can just echo it when we want to return it to the client.

Advantage would be that I do not have to duplicate the send logic in server if I don't want to use the server object.
https://github.com/phly/http/blob/master/src/Server.php#L165

**Comment by weierophinney** [comment]
If you want to send headers, `__toString()` is exactly the *wrong* solution. What you're describing is a response _emitter_. I'll consider it.

(If you want a string representation, a renderer would make sense; I'll also consider that.)

**Comment by Mech7** [comment]
Ah you mean it is the wrong solution because it needs to check if the headers are already send?
I am not familiar with a response emitter how would that work?
Perhaps a send method instead a __toString inside the response object would be an option, it would make the response a bit easier to use.

```php
$response->send();
```

**Comment by weierophinney** [comment]
> it is the wrong solution because it needs to check if the headers are already send?

No, because it has side effects (header emission) other than casting the response to a string.

> Perhaps a send method instead a __toString inside the response object

Responses should not send themselves. The PSR-7 interfaces describe value objects without behavior. Behavior belongs elsewhere; this is part of the reason for the `Server` implementation in this component.

The solution I proposed would be something more like:

```php
Emitter::emitResponse($response);
```

`Server` could delegate to that, essentially, and other code could simply invoke it.

**Comment by Mech7** [comment]
That would be fine too I guess :) though I have to say practically I don't really see the problem with doing it in the response though, it would make the interface easier to use and understand, save a bit of typing make it easier to have an isSent method in the response which could be useful if several parts of code are using the same response object.

Else you would probably get something like:

```php
$emitter = new Emitter($response);
$emitter->send();
// Some other piece of code
if (!$emitter->isSent()) {
}
```
Then you would end up with passing the emitter object everywhere in the application.

**Comment by trowski** [comment]
> Then you would end up with passing the emitter object everywhere in the application.

I'm not sure why you would be passing the `Emitter` object around, since it would only be responsible for sending the response as one of the final actions of a script after the response was completely built . Why would you be needing to constantly check if the response was sent?

The response object should *not* be responsible for sending itself as there are a variety of ways to send a response. Each way of sending a response should not require a different response class, but rather different objects that can encode and send an HTTP message depending on context.

The `Server` class in this package is a good example of why the responsibility for sending a response should be handled by a separate class. The `Server` class is sending the response in the context of running PHP as an Apache or Nginx module. But this is just one way a response object might be sent.

For an example of another context in which HTTP messages might be handled, look at the [HTTP component](//github.com/icicleio/Http/tree/master/src) I'm building for Icicle. Encoding an HTTP message is handled by the `Encoder` class which is used by the `Server` class before sending the response (this time over a TCP socket).

**Comment by Mech7** [comment]
Ah you mean you do something different then just output it then to stdout ? I never really thought that was an option if so i guess using it into a seperate object would be more better.

Btw I don't mean constantly checking the response, but I have come across situations where the response is either directly send in the controller to short circuit the application if it's not it would be send automatically at a later stage but there are always different ways to work around this :)
