### ISSUE TITLE
PHPStorm type hinting issue for Response

### ISSUE THREAD

**Issue by acelot** [phly/http#69]
This is OK:
```php
$response = (new Response())->withStatus($status)->withHeader('Location', $url);
```

And this is NOT:
```php
$response = (new Response())->withHeader('Location', $url)->withStatus($status);
```

PHPStorm mark `withStatus` method as wrong:
```
Method 'withStatus' not found in class \Phly\Http\MessageTrait
```

**Comment by weierophinney** [comment]
That's something you're going to need to bring up with PHPStorm, then. It should be resolving the return value from a method invoked from a trait based on the class that composes the trait.

**Comment by danizord** [comment]
@weierophinney I think the `return self` is referring the trait itself.
Maybe `return static`, `return MessageInterface` or even only `{@inheritDoc}` works.

**Comment by weierophinney** [comment]
@danizord I asked Mike van Riel what we should return, and he indicated `self` should resolve correctly, which is why I suggested that it's likely an issue with how Storm processes the docblocks. If you find something that works, feel free to open a PR; I'm not going to try and guess what will work.

**Comment by acelot** [comment]
Found an issue in PHPStorm bugtracker:
https://youtrack.jetbrains.com/issue/WI-17671
